version: "2"
volumes:
  database-data:
services:
  docker-ecosystem-migration:
    image: ${REGISTRY_HOST}/docker-ecosystem-migration:${IMAGE_TAG}
    build: .
    links:
      - database
  database:
    image: postgres:9.5.1
    ports:
      - '5432'
    volumes:
      - database-data:/var/lib/postgres/data
