version: "2"
volumes:
  database-data:
services:
  docker-ecosystem-migration:
    image: ${IMAGE_REGISTRY}/docker-ecosystem-migration:${IMAGE_VERSION}
    build: .
    links:
      - database
  database:
    image: postgres:9.5.1
    ports:
      - '5432'
    volumes:
      - database-data:/var/lib/postgres/data
